# Generated by Django 3.1.4 on 2021-03-11 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_location_locationzone_locationzonepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
