# Generated by Django 3.1.4 on 2021-03-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0005_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='municipality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
