# Generated by Django 3.1.4 on 2021-03-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0006_profile_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationzone',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
