# Generated by Django 3.1.4 on 2021-03-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0007_locationzone_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='on_route',
            field=models.BooleanField(default=False),
        ),
    ]
