# Generated by Django 3.1.4 on 2021-03-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0008_user_on_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='on_route',
            field=models.BooleanField(default=True),
        ),
    ]
